CREATE TABLE work_order_history (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    work_order_id BIGINT NOT NULL,

    old_status VARCHAR(30),

    new_status VARCHAR(30) NOT NULL,

    changed_by BIGINT NOT NULL,

    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_work_order_history_work_order
        FOREIGN KEY (work_order_id)
        REFERENCES work_orders(id),

    CONSTRAINT fk_work_order_history_user
        FOREIGN KEY (changed_by)
        REFERENCES users(id)

);